name: CIFuzz
on: 
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'rfcs/**'

permissions: {}

jobs:
 Fuzzing:
   runs-on: ubuntu-latest
   permissions:
     security-events: write
   steps:
   - name: Build Fuzzers
     id: build
     uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@be05d9598f9d9b5998b3846b50b7b49a1468e2a5
     with:
       oss-fuzz-project-name: 'go-git'
       language: go
   - name: Run Fuzzers
     uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@be05d9598f9d9b5998b3846b50b7b49a1468e2a5
     with:
       oss-fuzz-project-name: 'go-git'
       language: go
       fuzz-seconds: 300
       output-sarif: true
   - name: Upload Crash
     uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
     if: failure() && steps.build.outcome == 'success'
     with:
       name: artifacts
       path: ./out/artifacts
   - name: Upload Sarif
     if: always() && steps.build.outcome == 'success'
     uses: github/codeql-action/upload-sarif@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4.37.0
     with:
      # Path to SARIF file relative to the root of the repository
      sarif_file: cifuzz-sarif/results.sarif
      checkout_path: cifuzz-sarif
