on: [push, pull_request]
name: Git Compatibility
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        git: [[master, ubuntu-latest], [v2.11.0, ubuntu-latest]]

    runs-on: ${{ matrix.git[1] }}
    env:
        GIT_VERSION: ${{ matrix.git[0] }}
        GIT_DIST_PATH: .git-dist/${{ matrix.git[0] }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: sudo apt-get install gettext

    - name: Git Build
      run: make build-git

    - name: Set Git config
      run: |
        git config --global user.email "gha@example.com"
        git config --global user.name "GitHub Actions"
        export PATH=$GIT_DIST_PATH:$PATH

    - name: Test
      env:
        GIT_EXEC_PATH: ${{ github.workspace }}/${{ env.GIT_DIST_PATH }}
      run: make test-coverage
