name: Test
on:
  workflow_dispatch:
  push:
    branches:
    - releases/v5.x
    - main
    paths-ignore:
    - '**.md'
    - 'rfcs/**'
  pull_request:
    paths-ignore:
    - '**.md'
    - 'rfcs/**'

permissions: {}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [oldstable, stable]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    permissions:
      contents: read

    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

    - name: Install Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version: ${{ matrix.go-version }}

    - name: Configure known hosts
      continue-on-error: true
      if: matrix.platform != 'ubuntu-latest'
      run: |
        mkdir -p  ~/.ssh
        ssh-keyscan -H github.com > ~/.ssh/known_hosts

    - name: Set Git config
      run: |
        git config --global user.email "gha@example.com"
        git config --global user.name "GitHub Actions"

    - name: Validate
      run: make validate

    - name: Test
      run: make test

  test-wasi:
    strategy:
      fail-fast: false
      matrix:
        go-version: [oldstable, stable]

    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

    - name: Install Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install Wasmtime
      uses: bytecodealliance/actions/wasmtime/setup@9152e710e9f7182e4c29ad218e4f335a7b203613 # v1.1.3

    - name: Build
      run: |
        GOOS=wasip1 GOARCH=wasm go test -c -o go-git.wasm github.com/go-git/go-git/v6

    - name: Test
      run: |
        wasmtime run go-git.wasm -test.v -test.run '^TestWasmInit$' github.com/go-git/go-git/v6
